module.exports = {
  versionGroups: [
    {
      dependencies: ['@workspace/*'],
      isIgnored: true,
    },
    {
      dependencies: [
        '@finografic/design-system',
        '@finografic/icons',
        '@finografic/md-lint',
        '@finografic/oxc-config',
        '@finografic/project-scripts',
        '@pandacss/dev',
        '@types/node',
        '@types/react',
        '@types/react-dom',
        'drizzle-kit',
        'drizzle-orm',
        'hono',
        'i18next',
        'oxfmt',
        'oxlint',
        'oxlint-tsgolint',
        'picocolors',
        'react',
        'react-dom',
        'syncpack',
        'tsx',
        'turbo',
        'typescript',
        'valibot',
        'vite',
        'vitest',
      ],
      packages: ['**'],
    },
  ],
};
