const config = {
  sortAz: [
    'bin',
    'contributors',
    'dependencies',
    'devDependencies',
    'keywords',
    'peerDependencies',
    'resolutions',
  ],

  sortFirst: [
    'name',
    'version',
    'private',
    'description',
    'keywords',
    'homepage',
    'bugs',
    'license',
    'author',
    'repository',
    'type',
    'main',
    'module',
    'types',
    'exports',
    'files',
    'scripts',
    'dependencies',
    'devDependencies',
    'peerDependencies',
    'optionalDependencies',
    'packageManager',
    'engines',
    'lint-staged',
  ],

  versionGroups: [
    {
      label: 'workspace packages - ignore',
      dependencies: ['@workspace/*'],
      isIgnored: true,
    },
    {
      label: 'pinned cross-workspace versions',
      dependencies: [
        '@finografic/md-lint',
        '@finografic/oxc-config',
        '@finografic/project-scripts',
        '@tailwindcss/vite',
        '@tanstack/react-query',
        '@tanstack/react-table',
        '@types/node',
        '@types/react',
        '@types/react-dom',
        'drizzle-kit',
        'drizzle-orm',
        'hono',
        'i18next',
        'i18next-browser-languagedetector',
        'i18next-http-backend',
        'oxfmt',
        'oxlint',
        'oxlint-tsgolint',
        'picocolors',
        'react',
        'react-dom',
        'react-i18next',
        'react-router-dom',
        'syncpack',
        'tailwindcss',
        'tsdown',
        'tsx',
        'turbo',
        'typescript',
        'valibot',
        'vite',
        'vitest',
      ],
      packages: ['**'],
    },
  ],

  semverGroups: [
    {
      label: 'workspace refs - ignore semver',
      dependencies: ['@workspace/*'],
      isIgnored: true,
    },
    {
      label: 'all dependencies use caret ranges',
      range: '^',
      packages: ['**'],
      dependencies: ['**'],
    },
  ],
};

export default config;
